### ISSUE TITLE
Wrong URL for rbiomirgs_mrnascan

### ISSUE THREAD

**Issue by vincent-van-hoef** [jzhangc/git_RBiomirGS#1]
Thanks for this useful package!

Just a small remark; it seems that the url for the scan function needs to be "http://multimir.org/cgi-bin/multimir_univ.pl" instead of "http://multimir.org/" for the function to return results...

**Comment by liamhawkins** [comment]
Just came to write a pull request indicating this! Can confirm that new URL works

**Comment by jzhangc** [comment]
Thanks for the posts. Much appreciated!
