### ISSUE TITLE
Error with rbiomirgs_histogram function

### ISSUE THREAD

**Issue by Rabouali75** [jzhangc/git_RBiomirGS#2]
Hi
thanks for this useful package.

I'm trying to proceed like User Manual but for but for creating an Histogram i have a problem.

i have this error:

# Histogram of all gene sets 
```
 rbiomirgs_histogram(gsadfm = my_data_enrichment_GS, n = "all", 
                     y.rightside = TRUE, yTxtSize = 8, plotWidth = 300, plotHeight = 200, 
                     xLabel = "Gene set", yLabel = "model coefficient")
```
Error in rbiomirgs_histogram(gsadfm = my_data_enrichment_GS, n = "all",  : 
  could not find function "rbiomirgs_histogram"

**Comment by jzhangc** [comment]
Thanks for the comment. I will investigate.

**Comment by jzhangc** [comment]
Please try: rbiomirgs_bar() function instead. I have also updated the package with ggplot2 (>= 3.5.0) compatibility.
